name: Build and Push Docker Image to Alibaba Cloud Container Registry

on:
  push:
    branches:
      - main  # 触发条件：只在main分支推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # 下载代码

      - name: Build Docker Image
        run: docker build -t chat-git-image:latest .
        # 构建Docker镜像

      - name: Login to Docker Hub
        run: |
            echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        # 使用GitHub Secrets中的Docker Hub用户名和密码登录到Docker Hub
          

      - name: Tag image
        run: docker tag chat-git-image:latest 3011549907/chat-git-image:latest
       # 给镜像打上标签


      - name: Push Docker Image to Docker Hub
        run: docker push 3011549907/chat-git-image:latest
       # 上传到docker hub上的镜像

      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Install SSH Key
        run: |
          echo "$SERVER_SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        # 使用 GitHub Secrets 中的 SERVER_SSH_KEY，将私钥写入 ~/.ssh/id_rsa 文件

      - name: SSH into Alibaba Cloud ECS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@8.130.91.230

