name: chat-git
#当提交代码触发
on: [push]

#当主分支下的src改变的时候才会触发
#on:
#  push:
#    branches:
#    - master
#    paths:
#    - src/*
#还有计时功能，根据业务需求使用
jobs:
  job1: #也可以用默认的的job
    runs on: ubuntu-latest #这个是运行的时候依赖的系统，必须选择一个，且是github提供的系统
    steps:             #在什么样的系统下运行什么样的指令
#    - run: git clone   #拷贝代码下来，比较复杂，因为还有cd 之类的  可以用github默认提供的
#一个 -  代表一个数组
    - users: actions/checkout@v1    #github已经下载下来的流程
#    - users: actions/setup-node@v1  #设置环境，这里设置的是node的环境
#    - run: echo hello

  job2:
    need: job1  #只有在job1执行完以后才能执行
