name: Build and Push Docker Image to Alibaba Cloud Container Registry

on:
  push:
    branches:
      - main  # 触发条件：只在main分支推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # 下载代码

      - name: Build Docker Image
        run: docker build -t chat-git-image:latest .
        # 构建Docker镜像

      - name: Login to Docker Hub
        run: |
            echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          # 使用GitHub Secrets中的Docker Hub用户名和密码登录到Docker Hub
          

      - name: Tag image
        run: docker tag chat-git-image:latest 3011549907/chat-git-image:latest



      - name: Push Docker Image to Docker Hub
        run: docker push 3011549907/chat-git-image:latest

      # 登录到阿里云容器镜像仓库，下载镜像并运行容器
      - name: Login Alibaba
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login --username ${{ secrets.ACR_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin

      - name: Pull Image
        run: docker pull 3011549907/chat-git-image:latest

      - name: Run Image
        run:  docker run -e HOST_IP=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | head -1) -p 8080:8080 --restart=always -it --name chat-container 3011549907/chat-git-image:latest
